/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import MODEL.History;
import MODEL.UIDATA;
import java.awt.Image;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author bharv
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    History history;
    
    public CreateJPanel(History history) {
        initComponents();
        this.history = history;
    }

    CreateJPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        FN = new javax.swing.JLabel();
        EID = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        G = new javax.swing.JLabel();
        SD = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        TI = new javax.swing.JLabel();
        PT = new javax.swing.JLabel();
        CPN = new javax.swing.JLabel();
        EMID = new javax.swing.JLabel();
        PH = new javax.swing.JLabel();
        FNT = new javax.swing.JTextField();
        EIDT = new javax.swing.JTextField();
        AT = new javax.swing.JTextField();
        GT = new javax.swing.JTextField();
        SDT = new javax.swing.JTextField();
        LT = new javax.swing.JTextField();
        TIT = new javax.swing.JTextField();
        PTT = new javax.swing.JTextField();
        CPNT = new javax.swing.JTextField();
        EMIDT = new javax.swing.JTextField();
        UpBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Create Records");

        FN.setText("Full Name:");

        EID.setText("Employee ID:");

        A.setText("Age:");

        G.setText("Gender:");

        SD.setText("Start Date:");

        L.setText("Level:");

        TI.setText("Team Info:");

        PT.setText("Position Title:");

        CPN.setText("Cell Phone Number:");

        EMID.setText("Email Id:");

        PH.setText("Photo:");

        FNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNTActionPerformed(evt);
            }
        });

        EIDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIDTActionPerformed(evt);
            }
        });

        UpBtn.setText("UPLOAD");
        UpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PH)
                    .addComponent(TI)
                    .addComponent(L)
                    .addComponent(SD)
                    .addComponent(G)
                    .addComponent(A)
                    .addComponent(EID)
                    .addComponent(FN)
                    .addComponent(CPN)
                    .addComponent(PT)
                    .addComponent(EMID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EMIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpBtn))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(SaveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AT, CPNT, EIDT, EMIDT, FNT, GT, LT, PTT, SDT, TIT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Title)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FN)
                    .addComponent(FNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EID)
                    .addComponent(EIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(AT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G)
                    .addComponent(GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SD)
                    .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L)
                    .addComponent(LT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TI)
                    .addComponent(TIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PT)
                    .addComponent(PTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPN)
                    .addComponent(CPNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMID)
                    .addComponent(EMIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PH)
                    .addComponent(UpBtn))
                .addGap(27, 27, 27)
                .addComponent(SaveBtn)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNTActionPerformed

    private void EIDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIDTActionPerformed

    private void UpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        
        String FullName = FNT.getText();
        String EmployeeID = EID.getText();
        String Age = AT.getText();
        String Gender = GT.getText();
        String StartDate = SDT.getText();
        String Level = LT.getText();
        String TeamInfo = TIT.getText();
        String PositionTitle = PTT.getText();
        String CellPhoneNumber = CPNT.getText();
        String EmailID = EMIDT.getText();
        JButton Photo = UpBtn;
        
        UIDATA ud = history.addnewrecords();
        
        ud.setFullName(FullName);
        ud.setEmployeeID(EmployeeID);
        ud.setAge(Age);
        ud.setGender(Gender);
        ud.setStartDate(StartDate);
        ud.setLevel(Level);
        ud.setTeamInfo(TeamInfo);
        ud.setPositionTitle(PositionTitle);
        ud.setCellPhoneNumber(CellPhoneNumber);
        ud.setEmailID(EmailID);
        ud.setPhoto(Photo);
        
        JOptionPane.showMessageDialog(this, "New Record Saved.");
        
        FNT.setText("");
        EIDT.setText("");
        AT.setText("");
        GT.setText("");
        SDT.setText("");
        LT.setText("");
        TIT.setText("");
        PTT.setText("");
        CPNT.setText("");
        EMIDT.setText("");
       
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JTextField AT;
    private javax.swing.JLabel CPN;
    private javax.swing.JTextField CPNT;
    private javax.swing.JLabel EID;
    private javax.swing.JTextField EIDT;
    private javax.swing.JLabel EMID;
    private javax.swing.JTextField EMIDT;
    private javax.swing.JLabel FN;
    private javax.swing.JTextField FNT;
    private javax.swing.JLabel G;
    private javax.swing.JTextField GT;
    private javax.swing.JLabel L;
    private javax.swing.JTextField LT;
    private javax.swing.JLabel PH;
    private javax.swing.JLabel PT;
    private javax.swing.JTextField PTT;
    private javax.swing.JLabel SD;
    private javax.swing.JTextField SDT;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TI;
    private javax.swing.JTextField TIT;
    private javax.swing.JLabel Title;
    private javax.swing.JButton UpBtn;
    // End of variables declaration//GEN-END:variables
}
