/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import MODEL.History;
import MODEL.UIDATA;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author bharv
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    History history;

    public CreateJPanel(History history) {
        initComponents();
        this.history = history;
    }
    
Image photo=null;
String filename=null;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        FN = new javax.swing.JLabel();
        EID = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        G = new javax.swing.JLabel();
        SD = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        TI = new javax.swing.JLabel();
        PT = new javax.swing.JLabel();
        CPN = new javax.swing.JLabel();
        EMID = new javax.swing.JLabel();
        PH = new javax.swing.JLabel();
        FNT = new javax.swing.JTextField();
        EIDT = new javax.swing.JTextField();
        AT = new javax.swing.JTextField();
        GT = new javax.swing.JTextField();
        LT = new javax.swing.JTextField();
        TIT = new javax.swing.JTextField();
        PTT = new javax.swing.JTextField();
        CPNT = new javax.swing.JTextField();
        EMIDT = new javax.swing.JTextField();
        UpBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        SDT = new com.toedter.calendar.JDateChooser();
        PH1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Create Records");

        FN.setText("Full Name:");

        EID.setText("Employee ID:");

        A.setText("Age:");

        G.setText("Gender:");

        SD.setText("Start Date:");

        L.setText("Level:");

        TI.setText("Team Info:");

        PT.setText("Position Title:");

        CPN.setText("Cell Phone Number:");

        EMID.setText("Email Id:");

        PH.setText("Photo:");
        PH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        FNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNTActionPerformed(evt);
            }
        });

        EIDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIDTActionPerformed(evt);
            }
        });

        UpBtn.setBackground(new java.awt.Color(0, 0, 0));
        UpBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpBtn.setText("UPLOAD");
        UpBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBtnActionPerformed(evt);
            }
        });

        SaveBtn.setBackground(new java.awt.Color(0, 0, 0));
        SaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        SaveBtn.setText("SAVE");
        SaveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(PH)
                        .addGap(18, 18, 18)
                        .addComponent(UpBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PH1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SD)
                            .addComponent(G)
                            .addComponent(A)
                            .addComponent(EID)
                            .addComponent(FN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EIDT)
                            .addComponent(AT)
                            .addComponent(GT)
                            .addComponent(FNT)
                            .addComponent(SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TI)
                            .addComponent(L)
                            .addComponent(CPN)
                            .addComponent(PT)
                            .addComponent(EMID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LT, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(TIT)
                            .addComponent(PTT)
                            .addComponent(CPNT)
                            .addComponent(EMIDT))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FN)
                            .addComponent(FNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EID)
                            .addComponent(EIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A)
                            .addComponent(AT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(G)
                            .addComponent(GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L)
                            .addComponent(LT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TI)
                            .addComponent(TIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PT)
                            .addComponent(PTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPN)
                            .addComponent(CPNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EMID)
                            .addComponent(EMIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PH)
                    .addComponent(UpBtn)
                    .addComponent(PH1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(SaveBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNTActionPerformed

    private void EIDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIDTActionPerformed

    private void UpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        try {
            photo = ImageIO.read(f);
        } catch (IOException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        PH1.setText(f.getAbsolutePath());
    }//GEN-LAST:event_UpBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:

        String FullName = FNT.getText();
        String EmployeeID = EIDT.getText();
        String Age = AT.getText();
        String Gender = GT.getText();
        Date StartDate = SDT.getDate();
        String Level = LT.getText();
        String TeamInfo = TIT.getText();
        String PositionTitle = PTT.getText();
        String CellPhoneNumber = CPNT.getText();
        String EmailID = EMIDT.getText();
        JButton Photo = UpBtn;

        if (!Validation()) {

            //JOptionPane.showMessageDialog(this, "New Record Saved.");
        } else {

            UIDATA ud = history.addnewrecords();

            ud.setFullName(FullName);
            ud.setEmployeeID(EmployeeID);
            ud.setAge(Age);
            ud.setGender(Gender);
            ud.setStartDate(StartDate);
            ud.setLevel(Level);
            ud.setTeamInfo(TeamInfo);
            ud.setPositionTitle(PositionTitle);
            ud.setCellPhoneNumber(CellPhoneNumber);
            ud.setEmailID(EmailID);
            ud.setPhoto(photo);

            JOptionPane.showMessageDialog(this, "New Record Saved.");

            FNT.setText("");
            EIDT.setText("");
            AT.setText("");
            GT.setText("");
            SDT.setToolTipText("");
            LT.setText("");
            TIT.setText("");
            PTT.setText("");
            CPNT.setText("");
            EMIDT.setText("");
            UpBtn.setDefaultCapable(true);
        }
    }//GEN-LAST:event_SaveBtnActionPerformed
    private boolean Validation() {
        boolean Validate = false;
        if (FNT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Full Name");
        } else {
            Validate = true;
        }
        if (EIDT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Employee ID");
        } else {
            Validate = true;
        }
        if (AT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Age");
        } else {
            Validate = true;
        }
        if (GT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Gender");
        } else {
            Validate = true;
        }
        if (LT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Level");
        } else {
            Validate = true;
        }
        if (TIT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Team Info");
        } else {
            Validate = true;
        }
        if (PTT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Postition Type");
        } else {
            Validate = true;
        }
        if (CPNT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your CellPhone Number");
        } else {
            Validate = true;
        }
        if (EMIDT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide your Email ID");
        } else {
            Validate = true;
        }
        return Validate;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JTextField AT;
    private javax.swing.JLabel CPN;
    private javax.swing.JTextField CPNT;
    private javax.swing.JLabel EID;
    private javax.swing.JTextField EIDT;
    private javax.swing.JLabel EMID;
    private javax.swing.JTextField EMIDT;
    private javax.swing.JLabel FN;
    private javax.swing.JTextField FNT;
    private javax.swing.JLabel G;
    private javax.swing.JTextField GT;
    private javax.swing.JLabel L;
    private javax.swing.JTextField LT;
    private javax.swing.JLabel PH;
    private javax.swing.JLabel PH1;
    private javax.swing.JLabel PT;
    private javax.swing.JTextField PTT;
    private javax.swing.JLabel SD;
    private com.toedter.calendar.JDateChooser SDT;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TI;
    private javax.swing.JTextField TIT;
    private javax.swing.JLabel Title;
    private javax.swing.JButton UpBtn;
    // End of variables declaration//GEN-END:variables
}
